// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATSsmY6g8plnzoPOVV_q296aRPqAHMTUI',
    appId: '1:934946913165:web:22d961a2c54d91a97b1bc4',
    messagingSenderId: '934946913165',
    projectId: 'worker-auth-2cec4',
    authDomain: 'worker-auth-2cec4.firebaseapp.com',
    storageBucket: 'worker-auth-2cec4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCek9KSBntvlJxkk7G_O6G6goUwixS-18',
    appId: '1:934946913165:android:abb0308077aafd9c7b1bc4',
    messagingSenderId: '934946913165',
    projectId: 'worker-auth-2cec4',
    storageBucket: 'worker-auth-2cec4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVHjtrsF8Ds8hkjSTJ2DJb56nYoY5mxQI',
    appId: '1:934946913165:ios:44bb4556e2c8a6c87b1bc4',
    messagingSenderId: '934946913165',
    projectId: 'worker-auth-2cec4',
    storageBucket: 'worker-auth-2cec4.appspot.com',
    iosClientId: '934946913165-h0qmvadhnsph6rafb2fboe3jsi3u7se7.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVHjtrsF8Ds8hkjSTJ2DJb56nYoY5mxQI',
    appId: '1:934946913165:ios:b0d579927def081a7b1bc4',
    messagingSenderId: '934946913165',
    projectId: 'worker-auth-2cec4',
    storageBucket: 'worker-auth-2cec4.appspot.com',
    iosClientId: '934946913165-smmsstlfo9l75fju5dhp4ucmlm7h66do.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
